### ISSUE TITLE
timeInServer command giving `Server not found` error

### ISSUE THREAD

**Issue by spencermehta** [Candeles/harmony-discord#1]
I'm trying to run `modtools timeInServer` and it keeps giving a `Server not found` error even though I've written both the server id and user id.

**Comment by Candeles** [comment]
Try it again with v0.3.0. I have changed it so that it splits the string rather than relying on the id numbers to all be 18 characters. It works for me, I hope it does for you!

**Comment by spencermehta** [comment]
I can't test if this works as since updating to v0.3.0 I'm getting an error on running the bot - `Cannot find module './src/Permissions.js'`

**Comment by Candeles** [comment]
yyyyup I'm an idiot. It should work now!

**Comment by spencermehta** [comment]
Yep, can confirm it's now working!

**Comment by spencermehta** [comment]
Hmm. It doesn't seem like it's actually finding the user's time in the server, but instead the bot's time in the server.

**Comment by Candeles** [comment]
I've been doing my best to keep that well documented.

It does not appear that there is a counter via discord that keeps track of how long a user has been in server, which means the bot needs to keep track of it alone. It doesn't know when the user entered the server, so it keeps track starting when it starts keeping track of the user, which means either when the bot joins the server or when the user joins the server, occupied already by the bot.

According to my own tests on various servers, it *is* keeping track of the user's time in server individually, as accurately as it can. Let me know if you need more clarification or have a suggestion. This was just how I chose to solve the problem, and it's not quite a complete solution yet.
